-- Care Label System i18n Translations Export
-- Generated: 2026-02-26T00:39:45.295Z
-- 14 materials x 18 languages

DELETE FROM composition;
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('1', 'COTTON', 'algodón', 'coton', 'cotton', 'algodão', 'katoen', 'cotone', 'ΒΑΜΒΑΚΙ', 'コットン', 'baumwolle', 'bomuld', 'bombaž', '棉', '면', 'katun', 'قطن', 'algodón', 'cotó', 'kotoia');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('2', 'POLYESTER', 'poliéster', 'polyester', 'polyester', 'poliéster', 'polyester', 'poliestere', 'ΠΟΛΥΕΣΤΕΡΑΣ', 'ポリエステル', 'polyester', 'polyester', 'poliester', '聚酯纤维', '폴리에스터', 'poliester', 'بوليستير', 'poliéster', 'polièster', 'poliesterra');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('3', 'ELASTANE', 'elastano', 'élasthanne', 'elastane', 'elastano', 'elastaan', 'elastan', 'ΕΛΑΣΤΑΝΗ', 'エラスタン', 'elastan', 'elastan', 'elastan', '氨纶', '엘라스탄', 'elastan', 'إيلاستان', 'elastano', 'elastà', 'elastanoa');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('4', 'VISCOSE', 'viscosa', 'viscose', 'viscose', 'viscose', 'viscose', 'viscosa', 'ΒΙΣΚΟΖΗ', 'ビスコース', 'viskose', 'viskose', 'viskoza', '粘胶纤维', '비스코스', 'viskosa', 'فيسكوز', 'viscosa', 'viscosa', 'biskosea');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('5', 'NYLON', 'nailon', 'nylon', 'nylon', 'nylon (so p/o Brasil poliamida)', 'nylon', 'nailon', 'ΝΑΪΛΟΝ', 'ナイロン', 'nylon', 'nylon', 'najlon', '锦纶', '나일론', 'nilon', 'نايلون', 'nailon', 'niló', 'nylona');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('6', 'WOOL', 'lana', 'laine', 'wool', 'lã', 'wol', 'lana', 'ΜΑΛΛΙ', 'ウール', 'wolle', 'uld', 'volna', '羊毛', '울', 'wol', 'صوف', 'la', 'llana', 'artilea');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('7', 'SILK', 'seda', 'soie', 'silk', 'seda', 'zijde', 'seta', 'ΜΕΤΑΞΙ', 'シルク', 'seide', 'silke', 'svila', '丝绸', '실크', 'sutra', 'حرير', 'seda', 'seda', 'zetaa');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('8', 'LINEN', 'lino', 'lin', 'linen', 'linho', 'linnen', 'lino', 'ΛΙΝΑΡΙ', 'リネン', 'leinen', 'hør', 'lan', '亚麻', '린넨', 'linen', 'كتان', 'liño', 'lli', 'lihoaren');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('9', 'ACRYLIC', 'acrílico', 'acrylique', 'acrylic', 'acrílico', 'acryl', 'acrilico', 'ΑΚΡΥΛΙΚΟ', 'アクリル', 'acryl', 'akryl', 'akril', '腈纶', '아크릴', 'akrilik', 'أكريليك', 'acrílico', 'acrílic', 'akrilikoa');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('10', 'POLYAMIDE', 'poliamida', 'polyamide', 'polyamide', 'poliamida', 'polyamide', 'poliammide', 'ΠΟΛΥΑΜΙΔΙΟ', 'ナイロン', 'polyamid', 'polyamid', 'poliamid', '锦纶', '폴리아미드', 'poliamida', 'بولياميد', 'poliamida', 'poliamida', 'poliamida');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('11', 'MODAL', 'modal', 'modal', 'modal', 'modal', 'modal', 'modale', 'ΙΝΑ ΜΟΝΤΑΛ', 'モダル', 'modal', 'modal', 'modal', '莫代尔纤维', '모달', 'modal', 'شكلي', 'modal', 'modal', 'modala');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('12', 'BAMBOO', 'bambú', 'bambou', 'bamboo', 'bambu', 'bamboe', 'bambù', 'ΜΠΑΜΠΟΥ', '竹材', 'bambus', 'bambus', 'bambus', '竹', '대나무', 'bambu', 'الخيزران', 'bambú', 'bambú', 'banbu');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('13', 'CASHMERE', 'cachemira', 'cachemire', 'cashmere', 'caxemira', 'kasjmier', 'cashmere', 'ΚΑΣΜΙΡΙ', 'カシミア', 'kaschmir', 'kashmir', 'kašmir', '山羊绒', '캐시미어', 'kasmir', 'كشمير', 'caxemira', 'caixmir', 'kaxmirra');
INSERT INTO composition (id, material, spanish, french, english, portuguese, dutch, italian, greek, japanese, german, danish, slovenian, chinese, korean, indonesian, arabic, galician, catalan, basque) VALUES ('14', 'ALPACA', 'alpaca', 'alpaga', 'alpaca', 'alpaca', 'alpaca', 'alpaca', 'ΑΛΠΑΚΑΣ', 'アルパカ', 'alpaka', 'alpaka', 'alpaka', '羊驼毛', '알파카', 'domba', 'الألبكة', 'alpaca', 'alpaca', 'alpaka');
